#!/usr/bin/env python3
"""
edit-journal: Logs every file edit Claude makes to .claude/edit-journal.md.

Each entry records:
  - Timestamp
  - File path
  - Lines removed / added
  - One-line preview of what changed
"""
import json
import os
import sys
from datetime import datetime


MAX_PREVIEW = 120


def truncate(s: str) -> str:
    s = s.strip()
    return s[:MAX_PREVIEW] + "…" if len(s) > MAX_PREVIEW else s


def find_journal_path() -> str:
    """Write to .claude/edit-journal.md in cwd if the directory exists, else ~/.claude/."""
    local = os.path.join(os.getcwd(), ".claude")
    if os.path.isdir(local):
        return os.path.join(local, "edit-journal.md")
    return os.path.join(os.path.expanduser("~"), ".claude", "edit-journal.md")


def build_entry(tool: str, tool_input: dict) -> str | None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if tool == "Edit":
        file_path = tool_input.get("file_path", "")
        old = tool_input.get("old_string", "")
        new = tool_input.get("new_string", "")
        if not file_path:
            return None

        old_lines = old.strip().splitlines()
        new_lines = new.strip().splitlines()
        removed = len(old_lines)
        added = len(new_lines)
        change_desc = f"−{removed} / +{added} lines"

        old_preview = truncate(old_lines[0]) if old_lines else ""
        new_preview = truncate(new_lines[0]) if new_lines else ""

        lines = [
            f"\n## {timestamp}",
            f"**File:** `{file_path}`",
            f"**Change:** {change_desc}",
        ]
        if old_preview:
            lines.append(f"**Before:** `{old_preview}`")
        if new_preview:
            lines.append(f"**After:** `{new_preview}`")
        lines.append("\n---")
        return "\n".join(lines) + "\n"

    if tool == "Write":
        file_path = tool_input.get("file_path", "")
        content = tool_input.get("content", "")
        if not file_path:
            return None

        content_lines = content.strip().splitlines()
        added = len(content_lines)
        first_line = truncate(content_lines[0]) if content_lines else ""

        lines = [
            f"\n## {timestamp}",
            f"**File:** `{file_path}`",
            f"**Change:** New file, {added} lines",
        ]
        if first_line:
            lines.append(f"**First line:** `{first_line}`")
        lines.append("\n---")
        return "\n".join(lines) + "\n"

    return None


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    tool = data.get("tool_name", "")
    tool_input = data.get("tool_input", {})

    entry = build_entry(tool, tool_input)
    if not entry:
        sys.exit(0)

    journal_path = find_journal_path()

    try:
        # Write header on first use
        is_new = not os.path.exists(journal_path) or os.path.getsize(journal_path) == 0
        with open(journal_path, "a") as f:
            if is_new:
                f.write("# Claude Edit Journal\n\nAuto-generated by the `edit-journal` hookpm hook.\n")
            f.write(entry)
    except Exception:
        pass  # never block Claude

    sys.exit(0)


if __name__ == "__main__":
    main()
